### ISSUE TITLE
Grafiken steg 1

### ISSUE THREAD

**Issue by itpastorn** [TranemoGymnasieskola/Hangman#4]
Räkna ut antalet bokstäver i det ord man ska gissa på

Rita ett streck på canvasytan för varje bokstav. Du behöver använda en loop.

Hur du ritar förklaras här: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes

**Comment by LaVispera** [comment]
````javascript
     ctx.,beginPath();
     ctx.moveTo(firstLetterX, lettersY)
     // Loop där du
         // lineTo(letterWidth, lettersY)
         // moveTO(letterSpacing, lettersY)
      ctx.fill()
